name: working_time
description: Calculando o tempo.
publish_to: 'none'
version: 1.2.6+3

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  objectbox: ^2.4.0
  path_provider: ^2.1.2
  objectbox_flutter_libs: ^2.4.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  objectbox_generator: ^2.4.0

  flutter_lints: ^3.0.1

objectbox:
  output_dir: app/db/box_db

flutter:

  uses-material-design: true
  