// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../../app/core/database/models/sprint_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 3502888613888969157),
      name: 'SprintModel',
      lastPropertyId: const IdUid(5, 4421142804732401788),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2587144446244578833),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1717376104282320693),
            name: 'iDay',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 48116383981234739),
            name: 'fDay',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1832184975776415900),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4421142804732401788),
            name: 'days',
            type: 30,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 3502888613888969157),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    SprintModel: EntityDefinition<SprintModel>(
        model: _entities[0],
        toOneRelations: (SprintModel object) => [],
        toManyRelations: (SprintModel object) => {},
        getId: (SprintModel object) => object.id,
        setId: (SprintModel object, int id) {
          object.id = id;
        },
        objectToFB: (SprintModel object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final daysOffset = object.days == null
              ? null
              : fbb.writeList(
                  object.days!.map(fbb.writeString).toList(growable: false));
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.iDay);
          fbb.addInt64(2, object.fDay);
          fbb.addOffset(3, nameOffset);
          fbb.addOffset(4, daysOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = SprintModel(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              iDay: const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              fDay: const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              days: const fb.ListReader<String>(
                      fb.StringReader(asciiOptimization: true),
                      lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 12));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [SprintModel] entity fields to define ObjectBox queries.
class SprintModel_ {
  /// see [SprintModel.id]
  static final id =
      QueryIntegerProperty<SprintModel>(_entities[0].properties[0]);

  /// see [SprintModel.iDay]
  static final iDay =
      QueryIntegerProperty<SprintModel>(_entities[0].properties[1]);

  /// see [SprintModel.fDay]
  static final fDay =
      QueryIntegerProperty<SprintModel>(_entities[0].properties[2]);

  /// see [SprintModel.name]
  static final name =
      QueryStringProperty<SprintModel>(_entities[0].properties[3]);

  /// see [SprintModel.days]
  static final days =
      QueryStringVectorProperty<SprintModel>(_entities[0].properties[4]);
}
